# Generated by Django 6.0.4 on 2026-05-06 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la clase')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('codigo_union', models.CharField(help_text='Código único para que los estudiantes se unan a la clase.', max_length=8, unique=True, verbose_name='Código de unión')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('profesor', models.ForeignKey(limit_choices_to={'perfil__rol': 'PROFESOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de sesión')),
                ('timestamp_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de sesión')),
                ('intentos', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('pistas_dadas', models.JSONField(default=list, help_text='Lista de Seed_Questions entregadas durante la sesión.', verbose_name='Pistas dadas')),
                ('respondio_correctamente', models.BooleanField(default=False, verbose_name='Respondió correctamente')),
                ('fase_kst_alcanzada', models.PositiveIntegerField(default=1, help_text='Fase pedagógica máxima alcanzada (1-4).', verbose_name='Fase KST alcanzada')),
                ('historial_chat', models.JSONField(default=list, help_text='Lista de mensajes: [{"rol": "user"|"model", "texto": "..."}]', verbose_name='Historial del chat')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='tutor.clase', verbose_name='Clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Interacción IA',
                'verbose_name_plural': 'Interacciones IA',
                'ordering': ['-timestamp_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionIadov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '😞 Muy insatisfecho'), (2, '😕 Insatisfecho'), (3, '😐 Neutral'), (4, '🙂 Satisfecho'), (5, '🤩 Muy satisfecho')], verbose_name='Puntuación Iadov')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('interaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iadov', to='tutor.interaccionia', verbose_name='Interacción')),
            ],
            options={
                'verbose_name': 'Evaluación Iadov',
                'verbose_name_plural': 'Evaluaciones Iadov',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DiarioMetacognitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflexion_texto', models.TextField(help_text='¿Qué descubriste hoy sobre el tema?', verbose_name='Reflexión')),
                ('analisis_error_texto', models.TextField(blank=True, help_text='Explicación del error presentado en la Fase 4.', verbose_name='Análisis del error del compañero virtual')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('interaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diario', to='tutor.interaccionia', verbose_name='Interacción')),
            ],
            options={
                'verbose_name': 'Diario Metacognitivo',
                'verbose_name_plural': 'Diarios Metacognitivos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=10, verbose_name='Rol')),
                ('nombre_completo', models.CharField(blank=True, max_length=200, verbose_name='Nombre completo')),
                ('institucion', models.CharField(default='Colegio Sagrada Familia — COSAFAM', max_length=200, verbose_name='Institución')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tema', models.CharField(choices=[('FRACCIONES', 'Fracciones'), ('EXPONENCIACION', 'Exponenciación')], max_length=20, verbose_name='Tema')),
                ('nivel_kst', models.PositiveIntegerField(default=1, help_text='Posición en la jerarquía de conocimiento (1 = base).', verbose_name='Nivel KST')),
                ('enunciado', models.TextField(verbose_name='Enunciado del problema')),
                ('activacion_cognitiva_json', models.JSONField(help_text='JSON con la estructura: {"pregunta": "...", "opciones": ["A","B","C"], "correcta": "C"}', verbose_name='Activación cognitiva')),
                ('visualizacion_html', models.TextField(blank=True, help_text='Fragmento HTML con el componente visual animado de la Fase 1.', verbose_name='HTML de visualización')),
                ('expectations_json', models.JSONField(help_text='JSON: {"Expectations": ["Lo que el alumno debe deducir..."]}', verbose_name='Expectations (EMT)')),
                ('misconceptions_json', models.JSONField(help_text='JSON: {"Misconceptions": [{"error": "...", "Seed_Question": "Pregunta mayéutica..."}]}', verbose_name='Misconceptions (EMT)')),
                ('respuesta_correcta', models.CharField(help_text='Valor(es) aceptados como respuesta correcta, separados por coma.', max_length=200, verbose_name='Respuesta correcta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('prerequisito', models.ForeignKey(blank=True, help_text='El estudiante debe superar este problema antes de acceder al actual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='tutor.problema', verbose_name='Problema prerrequisito')),
            ],
            options={
                'verbose_name': 'Problema',
                'verbose_name_plural': 'Problemas',
                'ordering': ['tema', 'nivel_kst'],
            },
        ),
        migrations.AddField(
            model_name='interaccionia',
            name='problema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='tutor.problema', verbose_name='Problema'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='tutor.clase', verbose_name='Clase')),
                ('estudiante', models.ForeignKey(limit_choices_to={'perfil__rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['clase', 'fecha_ingreso'],
                'unique_together': {('estudiante', 'clase')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='interaccionia',
            unique_together={('estudiante', 'problema')},
        ),
    ]
